package com.example.shishusneh.ui.utils

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import android.net.Uri
import android.widget.Toast
import androidx.core.content.FileProvider
import com.example.shishusneh.data.entities.ActivityRecord
import com.example.shishusneh.data.entities.BabyProfile
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

class ReportManager(private val context: Context) {

    fun generatePdfReport(profile: BabyProfile, activities: List<ActivityRecord>, date: Date) {
        val document = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4 Size
        val page = document.startPage(pageInfo)
        val canvas: Canvas = page.canvas
        val paint = Paint()
        val dateFormat = SimpleDateFormat("dd MMM yyyy", Locale.getDefault())
        val timeFormat = SimpleDateFormat("hh:mm a", Locale.getDefault())
        val fileDateSuffix = SimpleDateFormat("dd_MMM_yyyy", Locale.getDefault()).format(date)

        // --- Header Section ---
        paint.color = Color.parseColor("#4A90E2")
        paint.textSize = 28f
        paint.isFakeBoldText = true
        canvas.drawText("Shishu-Sneh", 50f, 60f, paint)
        
        paint.color = Color.DKGRAY
        paint.textSize = 14f
        paint.isFakeBoldText = false
        canvas.drawText("Smart Baby Health Report", 50f, 80f, paint)

        // --- Baby Info Card ---
        paint.color = Color.LTGRAY
        canvas.drawRect(45f, 100f, 550f, 180f, paint.apply { style = Paint.Style.STROKE; strokeWidth = 1f })
        
        paint.color = Color.BLACK
        paint.textSize = 16f
        paint.isFakeBoldText = true
        canvas.drawText("Baby: ${profile.name}", 60f, 130f, paint)
        
        paint.isFakeBoldText = false
        paint.textSize = 12f
        canvas.drawText("Gender: ${profile.gender}", 60f, 150f, paint)
        canvas.drawText("Report Date: ${dateFormat.format(date)}", 60f, 170f, paint)

        // --- Activity Logs Section ---
        paint.textSize = 18f
        paint.isFakeBoldText = true
        paint.color = Color.parseColor("#4A90E2")
        canvas.drawText("Daily Activity Summary", 50f, 220f, paint)
        
        paint.color = Color.BLACK
        paint.strokeWidth = 2f
        canvas.drawLine(50f, 230f, 545f, 230f, paint)

        var y = 260f
        paint.textSize = 12f
        paint.isFakeBoldText = false

        if (activities.isEmpty()) {
            paint.color = Color.GRAY
            canvas.drawText("No activities recorded for this date.", 60f, y, paint)
        } else {
            activities.forEach { activity ->
                paint.color = Color.parseColor("#6C757D")
                canvas.drawText(timeFormat.format(Date(activity.timestamp)), 60f, y, paint)
                
                paint.color = Color.BLACK
                paint.isFakeBoldText = true
                canvas.drawText(activity.title, 130f, y, paint)
                
                paint.isFakeBoldText = false
                canvas.drawText("- ${activity.subtitle}", 200f, y, paint)
                
                if (activity.notes.isNotEmpty()) {
                    y += 18f
                    paint.color = Color.GRAY
                    paint.textSize = 10f
                    canvas.drawText("Note: ${activity.notes}", 130f, y, paint)
                    paint.textSize = 12f
                }

                y += 30f
                if (y > 780) return@forEach 
            }
        }

        // --- Footer ---
        paint.textSize = 10f
        paint.color = Color.LTGRAY
        canvas.drawText("Generated by Shishu-Sneh App", 220f, 820f, paint)

        document.finishPage(page)

        val fileName = "Baby_Report_${fileDateSuffix}.pdf"
        val file = File(context.cacheDir, fileName)

        try {
            document.writeTo(FileOutputStream(file))
            sharePdf(file)
        } catch (e: Exception) {
            Toast.makeText(context, "Export failed: ${e.message}", Toast.LENGTH_SHORT).show()
        } finally {
            document.close()
        }
    }

    private fun sharePdf(file: File) {
        val uri: Uri = FileProvider.getUriForFile(context, "${context.packageName}.provider", file)
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(intent, "Share Baby Report"))
    }
}
